### ISSUE TITLE
Trajectory file not generated

### ISSUE THREAD

**Issue by mouhyemen** [kjyv/FloBaRoID#1]
I installed all dependencies and individually tested if Python can import the libraries.

For the trajectory script (others as well), the trajectory file is not being generated. I am also getting warnings such as:
[WARNING] The iDynTree::Regressors::DynamicsRegressorGenerator class still needs to be migrated to
[WARNING] iDynTree native classes. To continue to use the iDynTree::HighLevel::DynamicsComputations class in the 
[WARNING] bindings in the current form, please compile iDynTree with the IDYNTREE_USES_KDL CMake option.
[WARNING] The iDynTree::Regressors::DynamicsRegressorGenerator class still needs to be migrated to
[WARNING] iDynTree native classes. To continue to use the iDynTree::HighLevel::DynamicsComputations class in the 
[WARNING] bindings in the current form, please compile iDynTree with the IDYNTREE_USES_KDL CMake option

Is the script dependent on this warning and that's why none of the trajectories are generated?? How did you solve this issue?

**Comment by kjyv** [comment]
Well, iDynTree was originally based on KDL and is still in the process of being modified to use only it's own code. As the iDynTree::Regressors::DynamicsRegressorGenerator class is used to generate the regressor and this code is still based on KDL, as the warning explains, you have to compile iDynTree with KDL.
Are these the only errors you receive? Please post the full output of e.g. the trajectory script if compiling with the IDYNTREE_USES_KDL flag does not help.

**Comment by mouhyemen** [comment]
These are all the options i get while compiling iDynTree. Where can I get enable the flag for IDYNTREE_USES_KDL?
Note: I also tried CoDyCo and did not find any KDL flags.
![idyntree_ccmake](https://user-images.githubusercontent.com/10107344/38038556-35c1d278-3279-11e8-93aa-8bc318d88376.png)

These are the warnings I get after running trajectory script:
![trajectory_warnings](https://user-images.githubusercontent.com/10107344/38038601-573a4d86-3279-11e8-8426-4619c39380a5.png)

I went through the code **identification/model.py** and 
```
# create generator instance and load model
self.generator = iDynTree.DynamicsRegressorGenerator()
ret = self.generator.loadRobotAndSensorsModelFromFile(urdf_file)

if not ret:
      sys.exit()
```

The system exits because **ret** is False.

**Comment by mouhyemen** [comment]
Hi,

Did you get a chance to look at the warnings?
Still waiting to hear back.

**Comment by traversaro** [comment]
Hi @mouhyemen , let me know if the modifications to idyntree-superbuild mentioned in https://github.com/robotology/idyntree/issues/427 helped you in solving this issue.

**Comment by mouhyemen** [comment]
Hey,
The build is failing currently on iDynTree superbuild project after adding the KDL option. I was going to just do a clean install from the superbuild but now this shows up

![image](https://user-images.githubusercontent.com/10107344/38100856-8ed37776-334c-11e8-9b38-1d46495280fa.png)

**Comment by mouhyemen** [comment]
Yes, issue solved.

**Comment by kjyv** [comment]
Great! I'm aware that the installation process is a bit of an effort. Also thanks for the help @traversaro ;)
Has the preferred method of installing iDynTree changed, especially considering the KDL dependency?
