### ISSUE TITLE
Extending the identification for mobile robots

### ISSUE THREAD

**Issue by padhupradheep** [kjyv/FloBaRoID#9]
Hey,

Is it possible to use your tool for a holonomic mobile robot?

**Comment by kjyv** [comment]
I guess it depends on the robot, but there should be no general reason against holonomic systems. I think the floating base identification theory was not conceived for e.g. wheels. A mobile snake-like system with six joints should work fine if you can measure all the contact forces.

**Comment by padhupradheep** [comment]
Basically it is valid only for a serial chain (linked) robot?

**Comment by kjyv** [comment]
Please read up on the theory (papers for the methods are mentioned, most robotics text books will also have the basics), the software is not of much use without that knowledge anyway. I haven't looked into identification of wheeled robots and I can just guess from what I've seen. I won't say it's impossible but the equations might need some changes or different constraints need to be applied.
